created landing page
EviveHealth/irhythm-fe pull request #3
Opened 2022-09-06 13:58 UTC by shanu798

created landing page

2022-09-06 14:25 UTC, vaibhavg15 requested changes

2022-09-06 14:25 UTC, vaibhavg15 commented on src/app.scss
> +    background-color: #E6E9F0;
Use semantic tokens for colors

2022-09-06 14:25 UTC, vaibhavg15 commented on src/features/landing/landingPageStatics.ts
> +    HEADER_TAG: 'WELCOME  TO KNOW YOUR RHYTHM',
change the name. header_tag is not appropriate

2022-09-06 14:25 UTC, vaibhavg15 commented on src/features/landing/landing-page.scss
> +      margin-bottom:3rem;
don't give margin-bottom. give margin-top to the lower element

2022-09-06 14:25 UTC, vaibhavg15 commented on src/features/landing/landing-page.scss
> +        gap: 1.3rem;
give individual margin-top to lower elements instead of this

2022-09-06 14:25 UTC, vaibhavg15 commented on src/features/landing/LandingPage.tsx
> +const getCard = (card:any) => (
we can create a new type for this

2022-09-07 06:41 UTC, rohan-1898 commented on src/features/landing/LandingPage.tsx
> +        <TextTitle  size={SIZE.XXL}>{LANDING_PAGE_STATICS.HEADING}</TextTitle>
add className and add text-color to it as it is given in mock

2022-09-07 06:56 UTC, rohan-1898 commented on src/features/landing/landing-page.scss
> +    gap: 3rem;
flex is not required here 
directly use the margin-top from "operation-container"
margin-top will be 6rem as per mock

2022-09-07 07:12 UTC, rohan-1898 commented on src/features/landing/landing-page.scss
> +        gap: 1.3rem;
use the margin-top value as per given in mock

2022-09-07 07:16 UTC, rohan-1898 commented on src/features/landing/landing-page.scss
> +        margin-top: 3rem;
use the margin-top value given in mock

2022-09-07 07:19 UTC, rohan-1898 commented on src/features/landing/landing-page.scss
> +        flex-direction: column;
display:flex is not required 
instead margin-top will work fine

2022-09-07 14:22 UTC, rohan-1898 commented
peer review done

2022-09-08 07:25 UTC, merged